Card.destroy_all

Card.create(
  [
    {
      letter:"a",
      url:"https://www.pinclipart.com/picdir/middle/569-5697320_transparent-apple-clip-art-red-apple-clipart-png.png"
    },
    {
      letter:"b",
      url:"https://cliparting.com/wp-content/uploads/2016/09/Cute-bus-clipart-kid-2.png"
    },
    {
      letter:"c",
      url:"https://www.vippng.com/png/detail/21-212690_free-download-high-quality-cartoon-cat-png-transparent.png"
    },
    {
      letter:"s",
      url:"https://www.pinclipart.com/picdir/big/4-40775_jaguar-pre-style-ergo-scissor-clip-art-purple.png"
    },
    {
      letter:"t",
      url:"https://creazilla-store.fra1.digitaloceanspaces.com/cliparts/845879/coal-train-clipart-md.png"
    },
    {
      letter:"z",
      url:"https://toppng.com/uploads/preview/baby-zebra-clipart-ba-zebra-clipart-zebra-i-love-animals-baby-zebra-clipart-115628585807kwannfvqb.png"
    }
  ]
)